


@startuml Teller Activity 

    start
    : Authentication Request ;
    : Join Available Tellers List ;
    if (Teller Available?) then (yes)
        : Receive List of Customers assigned to Teller ;
        if (List of Assigned Customers Empty or No New Joining Customer?) then (yes) 
            if (Transaction Complete?) then (yes)
                : Complete and Record Transaction ;
            else (no)
                : "Dismiss User and Record Cancelled Transaction" ;
            endif
        else (no)
        : Receive Empty List of Assigned Customers ;
        : Leave Available Tellers List ;
        : "Logout";
        end
        endif
    else (no)
        : Leave Available Tellers List ;
        : Logout ;
    endif
    end

    
    ' ' Teller
    ' Teller -> System : Authentication Request
    ' System -> queue_db : Lookup for Teller and verify password
    ' System -> queue_db : Add Teller to AvailableTellers table
    ' queue_db -> System : Provide Teller position
    ' System -> Teller : Show Users assigned
    ' Teller -> System : Record Transaction or Cancellation
    ' System -> queue_db : Remove user from Queue Table
    ' Teller -> System : Logout
    ' System -> queue_db : Remove Teller from AvailableTellers Table

    ' ' Manager
    ' Manager -> System : Extract Analytics Data
    ' System -> queue_db : Extract Transaction Data
    ' System -> System : Generate Analytics Report based on Transaction Data
    ' System -> Manager : Display Analytics Data


@enduml
