@startuml Class

interface CustomerData {
    String customerName
    String accountNumber
    String password
    String national_id
    void login()
    void logout()
}

interface GuestData {
    String customerName
    String telephone_number
    String password
    String national_id
    void includeGuest()
}

interface TellerData {
    String id
    String password
    void login()
    void logout()
}

struct TellerQueryData {
    String id
    int station
    int service_time
    bool active
    CustomerQueueData[] assigned_customers
    void recordTransaction()
    bool customerListEmpty()
    void recordCancellation()
    
}

struct Transaction {
    String detail
    String teller_id
    String client_national_id
    DateTime transaction_date
    int duration_seconds
    void generateAnalytics()
    void printAnalyticsData()
}


struct CustomerQueueData {
    String name
    String national_id
    String transaction_detail
    int position
    int sub_queue_position
    String assigned_server
    int server_location
    int time_duration_seconds
    DateTime time_joined
    void joinQueue()
    void leaveQsueue()
}


CustomerData  --|> CustomerQueueData
GuestData --|> CustomerQueueData 
TellerData --|> TellerQueryData

@enduml
