@startuml Customer Component
' !theme aws-Orange

[<<Object>> \n Customer] as customer
[<<UI>> \n Basic Auth] as auth
[<<UI>> \n Home] as home
[<<UI>> \n Navigation] as nav
[<<UI>> \n Enquiry Bot] as chatbot
[<<UI>> \n Queue Joining] as join
[<<UI>> \n User Queue Status] as status
[<<UI>> \n User Leaving] as leave

[<<System>> Assigner] as assign


customer --> auth  
auth --> home
auth --> chatbot
home <-- nav
auth <- nav
nav --> join
join --> status
status --> leave
leave --> auth


database "Queue Database" {
    [Auth Table] as auth_db
    [Queue Table] as queue_db
    [Server Table] as serve_db
    
}

auth_db -> auth
queue_db -> join
serve_db --> assign
assign --> join

@enduml